security:
    providers:
        backend_users:
            memory:
                users:
                    test: { password: '$argon2id$v=19$m=65536,t=4,p=1$AFQtWwffUtjBejsmPUrG+w$CoDtOTNXRTXPHIGvCKYhPz/fgaAotM0hEOEV2bgBKzE', roles: ['ROLE_ADMIN'] }
    encoders:
        Symfony\Component\Security\Core\User\User: auto

    firewalls:
        dev:
            pattern: ^/(_(profiadminler|wdt)|css|images|js)/
            security: false
        main:
            provider: backend_users
            http_basic:
                realm: Secured Area

    access_control:
