version: '3.8'

services:
  base:
    build:
      context: ./
      dockerfile: docker/base/Dockerfile
    image: git-history-base
  application:
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile
    image: git-history-dev
    volumes:
      - ./docker/dev/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - .:/home/git-history/project
    ports:
      - "80:80"
      - "8000:8000"
