services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Domain\Git: '@App\Adapter\Symfony\Process\Domain\GitTest'
